name: release
on:
  workflow_run:
    workflows: ["Build"]
    types: ["completed"]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate custom tag name
        id: generate_tag
        run: |
          DATE=$(date +'%Y%m%d%H%M%S')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          CUSTOM_TAG="release-${DATE}-${COMMIT_HASH}"
          
          echo "CUSTOM_TAG=${CUSTOM_TAG}"
          echo "::set-output name=custom_tag::${CUSTOM_TAG}" 

      - name: Create release with custom tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_tag.outputs.custom_tag }} 
          release_name: ${{ steps.generate_tag.outputs.custom_tag }}
          draft: false
          prerelease: false
