name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types: ["completed"]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact (api.zip)
        uses: actions/download-artifact@v3
        with:
          name: api  # Name must match the artifact name from the Build workflow

      - name: List files in artifact directory
        run: ls -la ./artifact  # Debugging step to list the files in the artifact directory

      - name: Generate custom tag name
        id: generate_tag
        run: |
          DATE=$(date +'%Y%m%d%H%M%S')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          CUSTOM_TAG="release-${DATE}-${COMMIT_HASH}"
          
          echo "CUSTOM_TAG=${CUSTOM_TAG}"
          echo "::set-output name=custom_tag::${CUSTOM_TAG}"

      - name: Create release with custom tag
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_tag.outputs.custom_tag }} 
          release_name: ${{ steps.generate_tag.outputs.custom_tag }}
          draft: false
          prerelease: false

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifact/api.zip  # Path to the downloaded artifact
          asset_name: api.zip  # Name of the uploaded artifact
          asset_content_type: application/zip
